namespace Up2dateConsole
{
    public enum Texts
    {
        GoodCertificateMessage,
        BadCertificateMessage,
        CannotStartInstallation,
        ServiceNotResponding,
        ServiceAccessError,
        DeviceNotInitialized,
        CertificateNotAvailable,
        NewPackageAvailable,
        NewPackageInstalled,
        PackageInstallationFailed,
        ClientUnaccessible,
        NoCertificate,
        ServerUnaccessible,
        AgentOrServerFilure,
        PackageStatusUnavailable,
        PackageStatusAvailable,
        PackageStatusDownloading,
        PackageStatusDownloaded,
        PackageStatusInstalling,
        PackageStatusInstalled,
        PackageStatusRestartNeeded,
        PackageStatusFailed,
        PackageStatusUnknown,
        FailedToAcquireCertificate,
        AddCertificateToWhiteList,
        InvalidCertificateForWhiteList,
        NoAnyWhitelistedCertificate,
        CertificateAddedToWhiteList,
        FailedToAddCertificateToWhiteList,
        LoadCertificate
    }
}
